# Generated by Django 6.1.1 on 2026-10-06 08:10

import assessments.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=assessments.models._new_public_id, editable=False, max_length=12, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Shown to candidates before they start.')),
                ('password_hash', models.CharField(blank=True, editable=False, max_length=256)),
                ('is_open', models.BooleanField(default=False, help_text='Candidates can only enter while the exam is open.')),
                ('exam_date', models.DateField(blank=True, help_text='If set, candidates can only start on this date (server time zone). Leave empty for any day.', null=True)),
                ('max_opens', models.PositiveSmallIntegerField(default=2, help_text='Opens allowed per candidate on one device. A refresh or reopen counts as an open.')),
                ('max_devices', models.PositiveSmallIntegerField(default=1, help_text='Different computers/browsers one candidate may use. 1 stops clearing browser data to get fresh opens.')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('max_violations', models.PositiveSmallIntegerField(default=5, help_text='The exam is submitted automatically at this many counted violations. 0 = never.')),
                ('penalties', models.JSONField(blank=True, default=assessments.models.default_penalties)),
                ('marks_mcq', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('marks_fill', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('marks_open', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('marks_match', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('show_results', models.BooleanField(default=True, help_text='Show the candidate their score on the result screen after submitting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, help_text='Optional: the module this assessment belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.module')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=150)),
                ('reg_no', models.CharField(max_length=60)),
                ('reg_no_display', models.CharField(blank=True, max_length=60)),
                ('access_key', models.CharField(default=assessments.models._new_access_key, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=12)),
                ('submit_reason', models.CharField(blank=True, choices=[('manual', 'Submitted by candidate'), ('time', 'Time ran out'), ('violations', 'Violation limit reached'), ('teacher', 'Submitted by trainer')], max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('answers_saved_at', models.DateTimeField(blank=True, null=True)),
                ('active_tab_token', models.CharField(blank=True, max_length=64)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('reset_epoch', models.PositiveIntegerField(default=0)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('penalty_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('objective_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('section_scores', models.JSONField(blank=True, default=dict)),
                ('open_marks', models.JSONField(blank=True, default=dict)),
                ('marking_complete', models.BooleanField(default=False)),
                ('trainer_comment', models.TextField(blank=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.exam')),
            ],
            options={
                'ordering': ['candidate_name', 'reg_no'],
            },
        ),
        migrations.CreateModel(
            name='PasswordFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('mcq', 'Multiple choice'), ('fill', 'Fill in the blank'), ('open', 'Open questions'), ('match', 'Matching')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.TextField()),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Relative weight inside its section.')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_at', models.DateTimeField(blank=True, null=True)),
                ('episode', models.CharField(blank=True, default='', max_length=40)),
                ('counted', models.BooleanField(default=True)),
                ('marks_deducted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='assessments.attempt')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('opens', models.PositiveSmallIntegerField(default=0)),
                ('first_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='assessments.attempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'device_id'), name='one_row_per_device')],
            },
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('exam', 'reg_no'), name='one_attempt_per_candidate'),
        ),
    ]
