# Generated by Django 6.1.1 on 2026-10-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_importdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_answers',
            field=models.BooleanField(default=False, help_text='Let candidates who have submitted review the correct answer to each question. Switch this on once every candidate has finished.'),
        ),
    ]
