# Generated by Django 6.1.1 on 2026-10-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_exam_show_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exam',
            name='closes_at',
            field=models.DateTimeField(blank=True, help_text='Late-entry cutoff: nobody can start after this time. Candidates already in progress can still reopen after a crash until their own time runs out.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='multi_scoring',
            field=models.CharField(choices=[('partial', 'Partial marks (right ticks minus wrong ticks)'), ('all', 'All or nothing')], default='partial', help_text='How “select all that apply” questions are marked.', max_length=8),
        ),
        migrations.AddField(
            model_name='exam',
            name='opens_at',
            field=models.DateTimeField(blank=True, help_text='Candidates cannot enter before this time.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_options',
            field=models.BooleanField(default=False, help_text='Each candidate sees multiple-choice options in a different order. A question with “all of the above” or “none of the above” is kept in order.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Each candidate sees the questions in a different order inside each section.'),
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=60)),
                ('reg_no_display', models.CharField(blank=True, max_length=60)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='assessments.exam')),
            ],
            options={
                'ordering': ['name', 'reg_no'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'reg_no'), name='one_roster_row_per_candidate')],
            },
        ),
    ]
