# Generated by Django 6.1.2 on 2026-10-08 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_attempt_layout_exam_closes_at_exam_multi_scoring_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='previous_attempts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=60)),
                ('reg_no_display', models.CharField(blank=True, max_length=60)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='assessments.classgroup')),
            ],
            options={
                'ordering': ['name', 'reg_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='one_class_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='classmember',
            constraint=models.UniqueConstraint(fields=('group', 'reg_no'), name='one_member_per_class'),
        ),
    ]
