# Generated by Django 6.1.2 on 2026-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_classes_and_retakes"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="mark_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="attempt",
            name="question_comments",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
