# Generated by Django 6.1.1 on 2026-09-19 04:41

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Folder-style key, e.g. GENCP302.', max_length=60)),
                ('code', models.CharField(help_text='Displayed module code.', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=99)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Short machine key, e.g. L4, L5NIT.', max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('kind', models.CharField(choices=[('trade', 'Trade'), ('archive', 'Archive')], default='trade', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=99)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('content_html', models.TextField(help_text='Sanitised HTML fragment — the lesson body, no page chrome.')),
                ('source_file', models.CharField(blank=True, help_text='Original file path this lesson came from, if imported.', max_length=400)),
                ('original_url', models.CharField(blank=True, max_length=400)),
                ('words', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveSmallIntegerField(default=1)),
                ('tables', models.PositiveSmallIntegerField(default=0)),
                ('images', models.PositiveSmallIntegerField(default=0)),
                ('code_blocks', models.PositiveSmallIntegerField(default=0)),
                ('headings_json', models.JSONField(blank=True, default=list)),
                ('search_text', models.TextField(blank=True, help_text='Plain text, used for search.')),
                ('order', models.PositiveSmallIntegerField(default=99)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word document'), ('text', 'Text'), ('code', 'Code / data'), ('image', 'Image'), ('video', 'Video'), ('assessment', 'Interactive assessment')], max_length=12)),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to=core.models.upload_resource_path)),
                ('external_path', models.CharField(blank=True, help_text='Used for imported legacy files served from static/legacy/.', max_length=400)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=99)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.module')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.trade'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. "LO2" or a topic slug.', max_length=40)),
                ('title', models.CharField(max_length=220)),
                ('kind', models.CharField(choices=[('outcome', 'Learning outcome'), ('topic', 'Topic')], default='outcome', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=99)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.module')),
            ],
            options={
                'ordering': ['order', 'code'],
                'unique_together': {('module', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LessonUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_unit_title', models.CharField(blank=True, max_length=220)),
                ('source_html', models.FileField(max_length=400, upload_to=core.models.upload_lesson_source_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html', 'htm'])])),
                ('original_filename', models.CharField(blank=True, max_length=260)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_record', to='core.lesson')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_uploads', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.module')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='core.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.unit'),
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'student activity',
                'ordering': ['-last_viewed'],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('trade', 'key')},
        ),
    ]
