# Generated by Django 6.1.1 on 2026-09-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word document'), ('text', 'Text'), ('code', 'Code / data'), ('image', 'Image'), ('video', 'Video'), ('assessment', 'Interactive assessment'), ('assignment', 'Assignment')], max_length=12),
        ),
    ]
