# Generated by Django 6.1.1 on 2026-09-19 13:40

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_resource_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=400, storage=core.models.private_storage, upload_to=core.models.upload_note_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'html', 'htm'])])),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML')], max_length=4)),
                ('original_filename', models.CharField(blank=True, max_length=260)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('content_html', models.TextField(blank=True, help_text='Sanitised HTML fragment (HTML notes only).')),
                ('search_text', models.TextField(blank=True)),
                ('headings_json', models.JSONField(blank=True, default=list)),
                ('words', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.module')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='core_module_is_publ_780fe3_idx')],
            },
        ),
    ]
