# Generated by Django 6.1.1 on 2026-09-23 06:49

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Optional — left blank, this defaults to the uploaded file's name.", max_length=220)),
                ('document', models.FileField(help_text='Upload an HTML (.html/.htm) or PDF (.pdf) file.', max_length=400, upload_to=core.models.upload_activity_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'html', 'htm'])])),
                ('document_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('html', 'HTML')], editable=False, max_length=4)),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=260)),
                ('size_bytes', models.PositiveIntegerField(default=0, editable=False)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished activities are hidden from students.')),
                ('order', models.PositiveSmallIntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.module')),
                ('topic', models.ForeignKey(help_text='The learning outcome / topic (within the selected module) this activity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.unit', verbose_name='Topic')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['order', 'title'],
            },
        ),
    ]
