# Generated by Django 6.1.1 on 2026-09-19 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.ForeignKey(blank=True, help_text="A student's current level, for a tailored dashboard.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.trade')),
                ('trainer_modules', models.ManyToManyField(blank=True, help_text='Leave empty to let a Trainer manage every module.', related_name='trainers', to='core.module')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
