# Generated by Django 6.1.1 on 2026-09-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_module_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trainer_modules',
            field=models.ManyToManyField(blank=True, help_text='Modules this Trainer may add notes to. Empty means none — a Trainer can also register their own modules when adding notes.', related_name='trainers', to='core.module'),
        ),
    ]
